version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webapplication
    # depends_on:
    #   - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8767:80
  # db:
  #   container_name: webappp_db
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Password
  #     MYSQL_DATABASE: webappdb
  #     MYSQL_USER: root
  #     ports:
  #       - 3334:3306
